server:
  port: 8080
  # Nếu không có, ứng dụng vẫn chạy trên cổng 8080, không cần thiết phải chỉ định
spring:
  application:
    name: NewsManagementSystem
    # Nếu không có, ứng dụng sẽ sử dụng tên mặc định là "application"
  datasource:
    url: "jdbc:mysql://localhost:3308/news_portal"
    # Nếu sai hoặc không có, có thể bị lỗi crash hoặc ném exception Cannot load JDBC driver or CommunicationsException or Access denied
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Nếu không có, có thể bị lỗi ClassNotFoundException hoặc NoClassDefFoundError.
    # Nếu url rõ ràng là MySQL, thì Spring Boot có thể đoán được driver.
    # Nhưng để an toàn và rõ ràng, nên khai báo.
    hikari:
      maximum-pool-size: 30         # Vì có thể có nhiều request đồng thời từ public
      minimum-idle: 10              # Đủ để phục vụ user lúc thấp điểm mà không giữ quá nhiều kết nối dư
      idle-timeout: 300000          # 5 phút - timeout cho connection không hoạt động
      max-lifetime: 1800000         # 30 phút - thay connection mới để tránh stale connection
      connection-timeout: 20000     # 20s - giảm timeout để nhanh fail khi DB nghẽn
      validation-timeout: 5000      # 5s kiểm tra connection còn sống
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Nếu không có, Hibernate sẽ cố gắng đoán, nhưng có thể suy luận sai dialect hoặc SQL không chuẩn → lỗi khi query hoặc insert.
    hibernate:
      ddl-auto: update
    show-sql: true
    # Nếu không có, sẽ không hiển thị SQL trong console, khó debug.
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
jwt:
  secret: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  access-token-expiration: 3600  # 1 hour
  refresh-token-expiration: 604800  # 7 days